### ISSUE TITLE
Helo missions and CTLD support

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2163]
To bring in some missions for rotor pilots the CTLD (https://github.com/ciribob/DCS-CTLD) script has to be integrated into liberation.
This issue is a placeholder for all the tasks to complete.

**Requirements**
- [x] Integrate CTLD plugin into liberation
- [x] Swap JTACAutolase to the ctld one
- [x] Rewrite of the LUAGenerator #2018 
- [x] exporting pilot names, pickup zones, dropoff zones, target zones to the lua data table (#412)
- [x] Load the pilots and zones from a lua script so that they will be created
- [x] Allow the AI commander to plan Helo missions
- [x] Make the AI capable to fly helo missions with ctld (preload troops)
- [x] Implement the F10 menu to fit liberation (prevent most stuff)
- [x] Special handling for carrier based operations (add all carriers as logistic unit, do not create a pickup waypoint and preload troops)

optional
- [ ] Take care of the economy balance (should users buy infantry groups which they can spawn in the mission?) optional
- [x] Spawn sling load crates for airlift missions (optional.. the actual mission does not have any effect. the result will not be tracked atm). This will also be required as a huey can not sling load a MBT so we have to fake it somehow
- [x] ~~Improve the sling load crates (currently i use the spawnCrateAtZone command from ctld but this can be changed to just use a cargo crate from the mission editor and space them randomly)~~
- [x] Add logistics unit to the pickup zone so that a client can spawn own crates there
- [ ] Track result of Airlift missions (did they arrive with the cargo?) and write to the state.json
- [ ] Parse the result of Airlift mission from liberation and decide if the transfer should be completed
- [ ] Improve the Airlift Planning to allow the user to choose the actual squadron / aircraft #1028
- [x] Target Zone for infantry troops (let them move towards the target) ->already working but the "waypoint zone" has to be a bigger radius as the drop off location has to be inside this zone so that the troops will move to the center of this zone
- [x] Show Zone radius on the map (like with the CAS waypoint)
- [ ] Improve Drop-off WP for AirAssault (faster flight and landing) - currently they are quite chilled during the approach. maybe this can be fine tuned
- [x] Add user option to use the default CTLD functions (by default they will be removed and tailored to only the mission specific needs)
- [ ] Fix / Improve the timing, speed and altitude of the flight plan. Can be done after the first implementation as it is fine tuning.

\
**Two missions can be implemented at first:**

Transport:
- [x] Transport mission (extend the current transfer system to enforce the creation of an airlift transport by the user)
- [x] Improve the UI: Add a dropdown for "Transport Type" where you can select "Auto" or "Airlift" instead of the checkbox.
- [x] Fix Airlift TOT Calculation / Startup time in the past
![grafik](https://user-images.githubusercontent.com/6678803/165146497-92795824-6943-4fc7-b393-485d1ba0d51c.png)

Air Assault (#527) :
- [x] AirAssault Mission Type
- [x] AirAssault Flightplan (Extension of the Airlift plan)
- [x] Calculation of Drop and Pickup Zones next to the Points. Easy way: Just a fixed distance away / towards the previous / next waypoint. Maybe add exception for AI flights that they use Takeoff and Assault waypoints as Pickup and Drop Off instead of specific zones. Problem is that we have to find a way to not set them in urban or forest area otherwise the AI will most likely just crash.
- [x] Adjust the F-10 menu to remove most of the CTLD functions and only add those needed to fulfill the mission. This can also be improved with a plugin specifc option to allow all CTLD function so that user can reuse this and do other things.

This airassault flightplan allows to have a separate pick up and drop off location. The CTLD zones will be placed at the Waypoint location with a 300ft radius. The drop off location must not be at the targeted CP. The CP has a target zone with a range of 1500ft (or more?) which will be used for the deployed troops as target where they will head to. So you can drop infantry out of the way of the defenses and let them fight theyre way to the FOB and shred some tanks with RPGs or similar.
![grafik](https://user-images.githubusercontent.com/6678803/163062176-4b5c2158-5ac9-4f94-ad70-360a3cb4a1a3.png)

\
More potential missions for later things
- [ ] CSAR missions for shot aircrafts and downed pilots. Create missions to recover pilots which ejected (find out if there is a way / event to recognize this. Update: https://wiki.hoggitworld.com/view/DCS_event_landing_after_ejection), https://github.com/ciribob/DCS-CSAR provides a toolkit including the beacon. Check if base CTLD has also these functions? Alredy existing Issue for CSAR: #1802
- [ ] Repair GroundObjects (SAM Sites, Factories and so on). Requires the Repair system at first. This mission could speed up the repair time or reduce the costs #1349
- [ ] Capture Buildings #2208 
- [ ] Rearm SAM Sites (not really meaningfull)
- [ ] Building FOBs

**Comment by Hornet2041** [comment]
> CSAR missions for shot aircrafts (Its fun but does not really fit the liberation game style as we do not really benefit of a recovered pilot atm

couldn't this tie into the existing pilot system? Recovering downed pilots could return them to the pool instead of having to wait for it being replenished by reinforcements

**Comment by DanAlbert** [comment]
If it doesn't the pilot feature was fairly pointless. That was always the motivation for doing it.

**Comment by RndName** [comment]
Good point (i never looked deeper into to the replenish function yet - shame on me i know :D)
Gonna update the issue later. Reading this the CSAR can have more sense i initially thought :)

**Comment by DanAlbert** [comment]
The replenishment aspect is part of it, but the skill level is important too. Even with instant replenishment it'd be worth rescuing veteran pilots.

(Limited replenishment remains optional because we haven't come up with an economic balance that anyone thinks is an improvement yet)

**Comment by SchmokedPancake** [comment]
A note on csar, it works and tracks shot down planes as is. 

Only thing to figure out is getting that event to liberation for squadrons replenishing. When they get shot down, or rescued (brought back to a fob or base) 

and of course creating missions for it that accommodate picking up pilots who got shot down.

**Comment by Abburo** [comment]
Some suggestions from my side if I'm allowed. I'm not a programmer but was looking for a proper CTLD/CSAR/FAC implementations for Liberation.  Not sure which will be your preferred programing env to create all these but  I've been looking on MOOSE framework which has a lot of features built in and easy to cover the requirements listed here. I would enumerate some:
1. MOOSE CTLD automatically reads pilots, units, triger zones etc, all it needs is just a naming alignment which is easy to get from Liberation
2. AI capabilities for CARGO/CSAR already present in Moose
3. possibility to create waypoints zones and patrol zones directly on  F10 map so that AI units will act by themselves after unloading
4. Integrated kind of unit limitations to be created directly in cargo definitions:
`my_ctld:AddTroopsCargo("Infantry Squad (6)",{"Infantry6"},CTLD_CARGO.Enum.TROOPS,6,soldierweight,2)`
The last number here  which is "2", says that there might be spawned only to Infantry squads. This could be converted somehow to some monetization I think.
5. Improved transport capabilities. A cargo unit can load multiple crates or troops as long the cargo capabilities definition are not exceeded. For example here a UH-60L can be set to transport more cargo crates then others, giving it more sense to be used.
6. Arty function (mortar mainly) can be integrated as well and might support the troops with illumination "bombs"

All above and more can be quite easy to integrate however there is on important issue to overcome. The way MOOSE working requires what is called "templates" of units with "late activation" checked so that they can be spawned from crates or other mean. I found out that Liberation campaign definition does not allow custom units to be set in so that they can be automatically used by Moose CTLLD during campaign progression. If some changes could be introduced on Liberation level I think it would be a fantastic addition an maybe a consistent way too add proper logistic .

If interested please just let me know and I can share my findings with you anytime ! Logistics in Liberation is something I really want to happen!

**Comment by RndName** [comment]
Thanks for the inputs!

Actually i was not planning to support MOOSE framework. It is a full blown Framework for mission scripting which we basicly do not use for liberation as we create all the mission from python using the pydcs framework. So no special scripting and dynamic editing / spawning of units is necessary for the general purpose of liberation (for now). The possibilites using Moose are huge (i personally use it as well for my personal dcs testing mission where i try out new stuff) but for me there is no real benefit which would justify the amount of work to be done to integrate it.

The real strenght of Moose (personal opinion) is to give Mission Designers super powerful tools to create long running dynamic, persistent campaigns

The normal CTLD (using mist) for now works really great for the kind of missions there will be (transport & air assault).

**Comment by SchmokedPancake** [comment]
Good work Rndname, this will bring a whole new role to be played out.
