### ISSUE TITLE
Push-based events overhaul

### ISSUE THREAD

**Issue by Raffson** [dcs-liberation/dcs_liberation#2263]
### Affected versions

Development build

### Description

Opening this issue to keep better track of the overhaul, labeling it (performance) bug/UX because fixing this will improve the UX since the map will update faster, more towards what we're used to from v5.2. Consider this as the first phase, effectively being a clean-up of `eventstream.tsx` to eliminate get-requests that are sent from the front-end as much as possible:

- [x] Navmesh updates (#2254)
- [x] Unculled zones (#2264)
- [x] Threat zones (#2254)
- [x] Updated flights (#2265)
- [x] Updated front lines (#2266)
- [x] Updated Tgos (#2269)
- [x] Updated IADS (#2262)
- [x] Updated control points (#2267)
- [x] Updated supply routes (#2255)
- [x] Combat updates: redundancies present (#2268)

Did I miss anything?

### Save game and other files

N/A
